"""initial migration

Revision ID: ac7f007f2828
Revises: 
Create Date: 2025-11-26 18:03:33.757480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac7f007f2828'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brands',
    sa.Column('brand_id', sa.UUID(), nullable=False),
    sa.Column('brand_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('brand_id'),
    sa.UniqueConstraint('brand_name')
    )
    op.create_table('countries',
    sa.Column('country_id', sa.UUID(), nullable=False),
    sa.Column('country_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('country_id'),
    sa.UniqueConstraint('country_name')
    )
    op.create_table('staffing_details',
    sa.Column('staffing_id', sa.UUID(), nullable=False),
    sa.Column('country', sa.String(length=50), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=False),
    sa.Column('band', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('staffing_id'),
    sa.UniqueConstraint('country', 'role', 'band', name='unique_country_role_band_staffing')
    )
    op.create_table('wbs',
    sa.Column('wbs_id', sa.UUID(), nullable=False),
    sa.Column('wbs_description', sa.Text(), nullable=False),
    sa.Column('wbs_weeks', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('wbs_id')
    )
    op.create_table('pricing_details',
    sa.Column('pricing_id', sa.UUID(), nullable=False),
    sa.Column('staffing_id', sa.UUID(), nullable=False),
    sa.Column('cost', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('sale_price', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['staffing_id'], ['staffing_details.staffing_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('pricing_id')
    )
    op.create_table('products',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('brand_id', sa.UUID(), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.brand_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('product_id')
    )
    op.create_table('wbs_staffing',
    sa.Column('wbs_id', sa.UUID(), nullable=False),
    sa.Column('staffing_id', sa.UUID(), nullable=False),
    sa.Column('hours', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['staffing_id'], ['staffing_details.staffing_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['wbs_id'], ['wbs.wbs_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('wbs_id', 'staffing_id')
    )
    op.create_table('offerings',
    sa.Column('offering_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('offering_name', sa.String(length=255), nullable=False),
    sa.Column('saas_type', sa.String(length=100), nullable=True),
    sa.Column('brand', sa.String(length=255), nullable=True),
    sa.Column('supported_product', sa.String(length=255), nullable=True),
    sa.Column('client_type', sa.String(length=255), nullable=True),
    sa.Column('client_journey', sa.String(length=255), nullable=True),
    sa.Column('client_journey_stage', sa.String(length=255), nullable=True),
    sa.Column('framework_category', sa.String(length=255), nullable=True),
    sa.Column('scenario', sa.String(length=255), nullable=True),
    sa.Column('ibm_sales_play', sa.String(length=255), nullable=True),
    sa.Column('tel_sales_tactic', sa.String(length=255), nullable=True),
    sa.Column('industry', sa.String(length=255), nullable=True),
    sa.Column('offering_tags', sa.Text(), nullable=True),
    sa.Column('content_page', sa.Text(), nullable=True),
    sa.Column('offering_sales_contact', sa.String(length=255), nullable=True),
    sa.Column('offering_product_manager', sa.String(length=255), nullable=True),
    sa.Column('offering_practice_leader', sa.String(length=255), nullable=True),
    sa.Column('business_challenges', sa.Text(), nullable=True),
    sa.Column('business_drivers', sa.Text(), nullable=True),
    sa.Column('offering_value', sa.Text(), nullable=True),
    sa.Column('tag_line', sa.Text(), nullable=True),
    sa.Column('elevator_pitch', sa.Text(), nullable=True),
    sa.Column('offering_outcomes', sa.Text(), nullable=True),
    sa.Column('key_deliverables', sa.Text(), nullable=True),
    sa.Column('offering_summary', sa.Text(), nullable=True),
    sa.Column('when_and_why_to_sell', sa.Text(), nullable=True),
    sa.Column('buyer_persona', sa.Text(), nullable=True),
    sa.Column('user_persona', sa.Text(), nullable=True),
    sa.Column('scope_summary', sa.Text(), nullable=True),
    sa.Column('duration', sa.String(length=50), nullable=True),
    sa.Column('occ', sa.Text(), nullable=True),
    sa.Column('prerequisites', sa.Text(), nullable=True),
    sa.Column('seismic_link', sa.Text(), nullable=True),
    sa.Column('part_numbers', sa.String(length=100), nullable=True),
    sa.Column('sale_price', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('created_on', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_on', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('offering_id')
    )
    op.create_table('activities',
    sa.Column('activity_id', sa.UUID(), nullable=False),
    sa.Column('offering_id', sa.UUID(), nullable=True),
    sa.Column('brand_id', sa.UUID(), nullable=True),
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.Column('activity_name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('part_numbers', sa.String(length=100), nullable=True),
    sa.Column('duration_weeks', sa.Integer(), nullable=True),
    sa.Column('duration_hours', sa.Integer(), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=True),
    sa.Column('is_mandatory', sa.Boolean(), nullable=True),
    sa.Column('outcome', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('effort_hours', sa.Integer(), nullable=True),
    sa.Column('fixed_price', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('created_on', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_on', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('client_responsibilities', sa.Text(), nullable=True),
    sa.Column('ibm_responsibilities', sa.Text(), nullable=True),
    sa.Column('assumptions', sa.Text(), nullable=True),
    sa.Column('deliverables', sa.Text(), nullable=True),
    sa.Column('completion_criteria', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.brand_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['offering_id'], ['offerings.offering_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('activity_id')
    )
    op.create_table('activity_wbs',
    sa.Column('activity_id', sa.UUID(), nullable=False),
    sa.Column('wbs_id', sa.UUID(), nullable=False),
    sa.Column('created_on', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.activity_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['wbs_id'], ['wbs.wbs_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('activity_id', 'wbs_id')
    )
    op.create_table('offering_activities',
    sa.Column('offering_id', sa.UUID(), nullable=False),
    sa.Column('activity_id', sa.UUID(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=True),
    sa.Column('is_mandatory', sa.Boolean(), nullable=True),
    sa.Column('created_on', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.activity_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['offering_id'], ['offerings.offering_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('offering_id', 'activity_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('offering_activities')
    op.drop_table('activity_wbs')
    op.drop_table('activities')
    op.drop_table('offerings')
    op.drop_table('wbs_staffing')
    op.drop_table('products')
    op.drop_table('pricing_details')
    op.drop_table('wbs')
    op.drop_table('staffing_details')
    op.drop_table('countries')
    op.drop_table('brands')
    # ### end Alembic commands ###
